### ISSUE TITLE
Initiate Synchronisation at startup

### ISSUE THREAD

**Issue by TheFog8** [MobiFlight/MobiFlight-Connector#1004]
After the start of Mobiflight or a restart of the simulator or the corresponding software, the state of the hardware switches can differ from the state in the software.

There is already a function that can be triggered but you have to assign it to an input of your hardware.

It would be nice if there could be a checkbox in the settings dialogue to enable an automatic synchronisation on startup.

**Comment by elral** [comment]
With firmware version 2.3.0 we introduced that all inputs gets initialized with there current status to avoid serial messages on start up which could avoid recognizing an Arduino from the connector.
Especially for the analog in this change gets recognized as before firmware 2.3.0 we had some serial messages with analog values until the average buffer was filled. All users using a pot for volume control recognize this change as now the volume will not be set the pot status.

We could also think about changing the firmware instead of the connector, e.g. once the config is read the retrigger function can be carried out. After reading the config the connector does not expect other messages than coming from inputs.
I personally would prefer that the connector "automatically" asks actively for the input stati.

**Comment by jetraid** [comment]
Could be  possible to read some sim variable to detect the fly status and then trigger the function to sync the switch. Some aircraft have a timer that run when the loading is finished.

**Comment by pizman** [comment]
@elral 
Is this a factor ?
The Retrigger not have do be done while boards are startup and connector look for boards.
Its much more logical to do this after we press RUN Button.   So far behind the initalize process.

To avoid a Conflict with all the Outputs (LED, Displays and so on) that need to be set within the first 1-2 Loops after press Run i would also think about a little "Delay".

Like in current system.... You Start MF,   You press RUN   and after some seconds you press the "Retrigger Button".

So i looking for a internal logic that say.... 
When user press RUN   ( Or Autorun is done) then after xxxx ms simply execute the already included Retrigger System 

In easy words... We just execute the feature  automatically after RUN   instead of await a user Input.
And NO.... I think it should not be executed after Sim Con is lost or when a Aircraft is loaded. 
For that case the user can remain the old logic with a button or can simply stop/Run MF once again !

**Comment by elral** [comment]
@pizman not sure what you mean.
> The Retrigger not have do be done while boards are startup and connector look for boards.
Exactly, this was also the reason to initalize the status of input device with the actual (physical) status of the inputs. Otherwise a couple/lot messages are generated in the first loop where the inputs are checked with the actual status against the saved (initialized) status. And this could disturb loading of the config.
As an example, one switch is closed and the input is LOW, but with firmware <2.3.0 the internal status was initialized with HIGH. During startup in the first loop the status of this input is checked and as the switch is closed the status is LOW, but internally it is HIGH. Therefore a status change is detected and a serial message is generated. With a lot of switches there could be also a lot of messages. With version 2.3.0 the internally status is initialized with the status the switch has.

For analog it's the same, before 2.3.0 the average buffer was initialized with 0. Every 10ms an analog value is read and the average buffer got filled (increased). The average buffer has 8 Bytes, so it takes 80ms to fill up the buffer. Every 50ms is checked, if the last value (average buffer) is different to the actual one. And as the buffer got filled up, a serial message was generated. So this was some kind of automatic retrigger.
With 2.3.0 the average  buffer gets initialized with the value coming from the pot and no change is detected on start up.
