### ISSUE TITLE
Change "by default" Tab for Input Configs

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#1129]
**Is your feature request related to a problem? Please describe.**
After creating a **new** _Input Config_ line and entering the Edit mode for the first time, by default the most left "precondition" Tab is shown. 

Assumption:
The first thing a user will do is select the Device and the input action.  Precondition is not needed as much because it is an optional settting.

**Describe the solution you'd like**
For a new config without defined Settings the "Input" Tab should be shown by default.... Not the "Precondition" Tab.

**Additional context**
After create the device and action on next time when i edit my config it show the "Input" tab directly as expected.
So logic should be the same for a "virgin" config, too.

**Comment by DocMoebiuz** [comment]
The order was done this way, because a precondition is evaluated BEFORE the input is evaluated, and the config references should be defined BEFORE the input action is evaluated. 

BUT... I also agree on your suggestion, the order should also be symetrical to the Output Config Wizard, where the Precondition Tab goes last. Precondition is a "optional" setting and "Config References" too. There is no "Config References" Tab yet on the Output Config Wizard. That would also make sense.

Note: I slightly updated your comment.
