### ISSUE TITLE
Add missing VID/PID Nano Every

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1227]
User WillemB reported to have a board that is not detected, please add it to MobiFlight with this information
Board is an Arduino Nano Every.
[https://store-usa.arduino.cc/products/arduino-nano-every?selectedStore=us](url)

**Provide the VID / PID combination**
Check the device manager for this information
VID: 2341
PID: 0058

**Provide type of board**
- [ x ] Arduino Nano

HOLD ANY ACTION HERE.  This board is apparently using the ATMEGA4809 processor, so it is not certain that it is compatible without recompiling the firmware.

I think the NANO EVERY should be classified simply as not supported.

**Comment by JaimeLeon2** [comment]
I think you can close this issue, unless someone thinks a firmware version should be developed for the Nano Every.

**Comment by neilenns** [comment]
@DocMoebiuz This would require a new firmware and I don't think anyone wants to support another Arduino variant right now :) Suggest closing.

**Comment by elral** [comment]
Oh, I wasn't aware of this issue.
There are less (unexpected) changes in the firmware code required to get it compiled.
Also this board needs additional parameters for avrdude, so I expect changes for the connector.
Maybe we could think about to have all parameters in the json file in one "string".

The biggest drawback of this board is the EEPROM size of 256byte. So the config is limited. Otherwise this is a nice board in regard of RAM and Flash.

**Comment by DocMoebiuz** [comment]
definitely low prio... i won't close it for now

**Comment by DocMoebiuz** [comment]
I will close it.
