### ISSUE TITLE
"Test" for 7 segment displays less than 8 digits doesn't work properly when Reverse is enabled

### ISSUE THREAD

**Issue by CaptainBobSim** [MobiFlight/MobiFlight-Connector#1251]
**Describe the bug**
If you switch number of digits from 8 to 6 the digits shown will include checked digits from 8.

Tested with a 6-digit module

**Steps To Reproduce**

Enable Reverse Digits

Click all 8 check boxes
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/76851401/bbc1bd94-536c-40ab-996e-247267110bd3)
Get 1.2.3.4.5.6 on module (7.8. are clipped off)

Change the number of digits to 6
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/76851401/20845131-3523-4a59-b7cd-25571fec76fd)

Press Test and get result
3.4.5.6.7.8.

Go back to 8 checkboxes to see why
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/76851401/010c48fa-e13f-4b71-a04f-ce4987fdc5d7)

**Expected behavior**
Going from 8 digits to 6 digits would ignore the last digits not the first digits. Maybe I am incorrect in my assumption

**Actual behavior**
First 2 digits ignored, starts at 3

**Details**
 - MobiFlight Version: 9.7.1

**Additional context**
Running actual simulator works perfectly!

**Comment by JaimeLeon2** [comment]
In Discord, user NonDiscrete reported encountering this issue with 3 and 5 digit Prop Wash 7 segment modules.  He exchanged messages and screenshots with Prop Wash but they could not find a solution.  Apparently the Prop Wash modules have the digits reversed.

**Comment by CaptainBobSim** [comment]
I forgot to mention my testing was with propwashsim as well.

**Comment by klarson18** [comment]
![Capture2](https://github.com/MobiFlight/MobiFlight-Connector/assets/18076629/84de4bc9-6513-4cbc-b065-44c5f1b7b3a7)
![Capture1](https://github.com/MobiFlight/MobiFlight-Connector/assets/18076629/3605a425-628f-40e7-9e0f-20112b5585e9)
![Capture](https://github.com/MobiFlight/MobiFlight-Connector/assets/18076629/6d9824ad-c24e-4504-ae5b-a02ab067ddf3)
![Capture4](https://github.com/MobiFlight/MobiFlight-Connector/assets/18076629/0ce2df32-e5c0-4c83-bafa-6c00785a2c2a)
![Capture3](https://github.com/MobiFlight/MobiFlight-Connector/assets/18076629/62aceab7-fb14-4412-9222-0bfb186070e0)
The issue seems to be in the test function.  Here are the screenshots for the 3 and 4 digit led's that we sell.  They are working without issue.  I did need to use the rounding function for the correct digits to show.  Without the rounding function it shows the last 3 or 4 digits way to the right of the decimal point
