### ISSUE TITLE
MAX7219 displays configured with fewer than eight digits don't display properly in 10.0

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1479]
**Describe the bug**
MAX7219 displays configured with fewer than eight digits don't display properly in 10.0

**Steps To Reproduce**
1. Configure a 7-segment display output with fewer than 8 digits in the `Number of digits` dropdown and reverse digits enabled
2. Hit the test button

**Expected behavior**
You see the test digits properly

**Actual behavior**
You don't

**Details**

Plenty of reports of this in Discord, [here's one with a detailed breakdown from Mike at SimpleFCU](https://discord.com/channels/608690978081210392/1183423789925679234). The workaround is to change the `Number of digits` dropdown to eight.

Not clear if reverse digits is required but Mike and I both had that setting on.

**Comment by DocMoebiuz** [comment]
We have the following work-around for this:

Config in 9.7.1
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/435c8007-a851-4c23-b51a-59ec77122fa5)

Config in 10.0
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/5356f30e-ff8e-479a-a7ac-66c5858dfd79)

The reverse logic has to be reviewed in general because also the old version doesn't cover all cases correctly.
See https://github.com/MobiFlight/MobiFlight-Connector/issues/1491
