### ISSUE TITLE
Slow Octavi encoder when DOF reality H2 control box connected

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#1725]
**Describe the bug**
When the DOF reality H2 control box is connected, the Octavi encoder events are very slow.

**Steps To Reproduce**
1. Connect DOF reality H2 control box
2. Connect Octavi
3. Enable logging
4. Turn encoders
5. See error

**Expected behavior**
Fast encoder events

**Actual behavior**
Slow encoder events

**Details**
 - MobiFlight Version: 10.0+

**Additional context**
Reported on Discord https://discord.com/channels/608690978081210392/1179151236277219409

**Comment by pdebaty** [comment]
Resolution posted on Discord: 
From Arnold:
I had this same issue. It was caused by Sim Racing Studio's automatic Com Port search of my DOF Reality H3. I fixed it by manually entering my H3's Com Port in "Documents\SimRacingStudio 2.0\config.ini" -> [DOF REALITY] left_controller_com_port = COM4

This fixed my issue as well.
