### ISSUE TITLE
Value does not display on LED segment unless it's changing when enabled.

### ISSUE THREAD

**Issue by korruptcow** [MobiFlight/MobiFlight-Connector#390]
I have a timer that rotates variables on a 7 segment LED. Issue comes in when I enable the varible with a precondition. If the value has not changed it stays blank until it updates. In this case i am using zulu hour to grab the hour and of course that value only changes once an hour. So all i seem to get is the minutes showing up. If i stop and stat MF it shows up on the screen. When it rotates back it's blank again.

If the value has not changed since the last enable it doesn't refresh the screen.

Example : zulu hour - 23 - I swap zulu hour variable , disable it with precondition. come back in 30 seconds and enable it again. Because hour is still 23 the screen just shows what ever was in the position at the time (blank or the last variable).

What probably needs to happen is on precondition met and the variable in enabled it needs to screen blank the digits and write the current value. Eg the minute value shows up because it changes in the time the value is enabled on the screen.

I can show this in action if required.

**Comment by korruptcow** [comment]
https://youtu.be/P9gUwpU37eU

It in action.

**Comment by Mobiflight** [comment]
Make sure you are using the same amount of digits for both output configurations. Then the change should work correctly.

Background: MobiFlight uses a local cache to not send all the data all the time to the Arduino boards. To create a cache entry for a configuration, and to be able to compare it, MF creates a unique key for the display. LED segments are special, because we can create a mask to only update a subset of digits.

Please confirm that this is the problem.

I will still try and see if we can fix this. Maybe it makes more sense to keep track of the value of the display as a whole and not on config level.

**Comment by korruptcow** [comment]
It seems to be a cache issue because if the variable is the same as last one on enable it won't display anything.
It does this for ANY variable that has not changed since the last call. You can see this on the video where temperature didnt update unless i changed it .. or the hour updates when i changed it.

Lets use an example from my config.

I have ambient temperature and ZULU time on the same 4 digits of the eight digit display.
Every 30 seconds I want to display either of the variables based on the Zulu seconds counter.

The first time around when it flips from disabled to enabled. (precondition) it will show the variable.
Example: ZULU HOUR = 14 ...  so it would display 14 on where it should.

30 seconds later I disable the variable and show temperature it will blank it out and show -10
30 seconds later I disable temperature and enable zulu hour again.

The hour is STILL 14 but because it has not changed since it has been enabled again it won't display anything just a blank.

So the solution is probably is if it cached as you say. On enable of the variable refresh the cache and output the variable displayed in the cache. Because the variable has not changed in that time. When its re-enabled the cache would be blank I guess.

Hope that helps. I can show another video or jump on discord if you want to me explain it more.

The counter wraps around and shows Ambient temperature which clears that varsible (if it has changed)

**Comment by korruptcow** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/30361335/124552267-a6bf6380-de76-11eb-9d00-bc158892f9c0.jpg)

**Comment by MobiFlight-Admin** [comment]
Thanks, your example explains and summarizes the problem well. I will double check because it should not behave this way. I am not caching on variable level but on LED Display module level, taking into account the used digits. If module & number of digits are set the same, then it always should change when the displayed value changes.

**Comment by MobiFlight-Admin** [comment]
@korruptcow - I can see the problem on you diagram now. You have to use 4 digits for both configs. 4 digits for temp, and you have to combine hour and second into one value and use 4digits. You can combine hours and minutes with config references and doing something like 

$*1000+# 

Where $ is the hours and # placeholder for the minutes

**Comment by korruptcow** [comment]
That looks like it worked. Thanks. I always have issues with the transforms though. But it's working as it should now :)

**Comment by MobiFlight-Admin** [comment]
Ok. Great! I will close this now.
