### ISSUE TITLE
Increase maximum size of output config variable field 

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#417]
**Is your feature request related to a problem? Please describe.**
Although not designed for scripts, the variable field can in fact run scripts for time dependent functions, taking advantage of MF refreshing outputs several times per second.  Currently there appears to be a size limitation where longer than a couple of lines scripts cause MF to start acting strangely.  An overflow of some sort inside MF is suspected.

**Describe the solution you'd like**
Increase the character holding capacity of the variable field to at least 1KB to be able to accommodate larger scripts.

**Describe alternatives you've considered**
There is no other way that I know to run scripts with (E:SIMULATION TIME) as a variable that can be managed as time progresses.  Normal event scripts only run once, so they are not feasible for time variables.

**Additional context**
Sample of the type of scripts I would like to be able to run... this is for a led that ramps up in brightness in 2 seconds, simulating some of the slow light indicators in the simulator.  An input config is used to set a toggle Lvar that starts the time dependent script.  It is also possible to call any K: or H: events from the variable field.

(L:my_btn01_on, bool) if{ (L:my_start) 0 == if{ (E:SIMULATION TIME, second) (>L:my_start) } (E:SIMULATION TIME, second) (L:my_start) - 2 < if{ (E:SIMULATION TIME, second) (L:my_start) - d * 255 * 255 min } els{ 255 } } els{ 0 }

It would be possible to simulate a sequence of actions that happen over time, but initiated from one button press.  For example, having a script to turn on all the fuel pumps, spaced 5 seconds each.

**Comment by Mobiflight** [comment]
At the moment the maximum script length is 256 characters

**Comment by JaimeLeon2** [comment]
Another use for output driven code, besides timed events, is to execute events based on a sim variable. For example, being able to have an auto deploy button for spoilers.
Another use case could be being able to set Lvars based on other Sim variables, without an input event happening, for example the TOGA button indicator mentioned in the Discord server.

**Comment by MobiFlight-Admin** [comment]
@JaimeLeon2 i really admire your creativity and finding this approach with all the stuff that might be possible, but I wonder if it is the right place and the right name for it or if it merits something more specifically built for it.

e.g. the feature is originally intended to work for LVars. MF WASM Module checks on every frame if the value has changed, there for it executes the code on every frame, compares the output and informs MF Connector about a change (in case one happened).

At the moment we are not seeming to have performance impact using this strategy, for LVars, and maybe even not for your approach.

I think we should describe what you are trying to achieve and see if there are other means to achieve them. 

Some disadvantages of the current approach:
* It is not user-friendly and more for advanced users
* It is kind of a hack
* It might impact performance or sim stability because of memory leaks or so
* It is not portable to other sims but only specific to MSFS2020

Idea:
* List the things you try to do and see if it makes sense to implement them as dedicated feature in MF

Note:
The increment of buffer space for the event length is also covered in https://github.com/MobiFlight/MobiFlight-Connector/issues/432 - of course this is the input side, but the code is related.

**Comment by MobiFlight-Admin** [comment]
@JaimeLeon2 an idea which is already discussed a couple of times is the need to have an "Input Action"-Output Device... if that makes sense. I mean, that we can trigger a input event at the end of an output configuration. This would likely cover the second use case.

Also writing the result of an output configuration back to an, e.g. MF Offset would then be possible, which has beend discussed before too.
