### ISSUE TITLE
Add support for input shift registers

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#449]
**Is your feature request related to a problem? Please describe.**
You can never have enough Arduino pins :) As we discovered with the output shift register work (#173) shift registers are an amazing addition to mobiflight. We're halfway there: output shift registers are done. But what about input?

**Describe the solution you'd like**
Support for input shift registers like the 74HC165.

**Describe alternatives you've considered**
Asking Arduino to make boards with more pins 😂

**Additional context**

Data sheet: https://www.ti.com/lit/ds/symlink/sn74hc165.pdf
PR for output shift registers: https://github.com/Mobiflight/MobiFlight-Connector/commit/871b55183078c5d59196b2ed15347c3d3c4f5064

**Comment by Mobiflight** [comment]
Another alternative is to buy another arduino board. :-)

For the output pins it makes sense because driving LEDs and such can be accomplished better with certain output shift registers which can be driven with a different power source for example.

Input expansion is a convenience feature - or at least at the moment I don't see a specific technical reason.

At the same time the step might not be huge to be able to add the inputs too.

**Comment by danecreekphotography** [comment]
I'm looking ahead to building an AP panel for the TBM930 with onboard ATMega32u4. It's a LOT of buttons to handle and I don't want to have to put two ATMegas on the board just to deal with it :)

I'm going to give a try at adding this in the next week or so. We'll see how far I get!

**Comment by danecreekphotography** [comment]
I've started on this. Woot!

**Comment by Mobiflight** [comment]
Hey cool! What's the criteria to choose this chip specifically? It's important to pick one which is available in a board format to the users. I can find only one such package on ebay but it's not very common.

I would really like to support the 74hc4067 https://www.instructables.com/Tutorial-74HC4067-16-Channel-Analog-Multiplexer-De/?amp_page=true

this would also allow xplane simvim users to transition to MobiFlight.

See https://github.com/Mobiflight/MobiFlight-Connector/issues/276

**Comment by danecreekphotography** [comment]
It's the most common input shift register used in Arduino tutorials. Not sure why you can't find one on ebay, there are lots. It's also widely available from aliexpress, tayda, lcsc, etc.

As with the output shift register support this will work with any input shift register that has a clock, latch, and data pin.

Multiplexer support would be cool but has a different addressing scheme than shift registers and would require different implementation.

**Comment by Mobiflight** [comment]
The chips are available - but a cheap breakout board version would be nice. Do they offer one? I only looked on ebay and couldn't find many options - but there are some.

We have to keep in mind that most of the users are not so savvy to work with bare ICs and would require something more friendly with pin headers to connect it via dupont cables.

**Comment by danecreekphotography** [comment]
Update: I have this working end-to-end with a single shift register. Need to do some testing with multiple shift registers and some code cleanup/refactoring.

**Comment by danecreekphotography** [comment]
Notes to myself:

* Make it work with analog pins
* Fix the display in the input tab so the selected pin is shown in the Input column

**Comment by MobiFlight-Admin** [comment]
Let's talk about the UI layout. I would like to keep things consistent. The drop down on the screenshot is not the way we do it for buttons.

If these are input shift registers I want to keep it analog to the buttons or if needed for the potentiometers if the pins are analog inputs.

We have to come up with a good way to define whether a pin is analog or digital and this should go into the device settings rather than in the config settings.

I think it would be best to have a discord voice session to discuss ideas.

With the output shift registers we were able to achieve the consistency in the UI, so i am confident we can get it done for the input shift registers too

**Comment by danecreekphotography** [comment]
Yep for sure we can chat! Adding the dropdown next to the device was just a quick way to do it without having to make any modifications to button Input Settings portion of the panel and prove the communications would work.

As it stands now on the input config side it's a copy of how button works (I copied all of the OnPress/OnRelease code for buttons) since that's really what the use of these is: adding lots and lots of buttons. The only difference between using a button and using a shifter is a need to specify which shifter pin to listen to (similar to specifying which output pin to send data to for an output shifter).

The analog pin thingy I mentioned is just a bug I think in how pins get saved/stored for a module config. Haven't looked into it, just stumbled on it by accident.

**Comment by danecreekphotography** [comment]
Demo of this working with 16 inputs (using new input shifter support) and 16 outputs (using existing output shifter support): https://photos.app.goo.gl/TQiqSfFjXYm9twMh7

**Comment by danecreekphotography** [comment]
Looks like as written the firmware code consumes 326 bytes of flash.

**Comment by danecreekphotography** [comment]
On hold until the PlatformIO work is done.

**Comment by Shand359** [comment]
This is such a cool direction for Mobiflight to take. I asked about this ages ago but was told it wasnt an option at that time. I am so very glad to see this being implemented.. Once its completed I will need to buy the corresponding hardware and get things reconfigured and working..... sadly i cannot do the technical side of things required to make this work myself..... well done..
