### ISSUE TITLE
Allow setting variables via simulator data

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#456]
Currently it seems to require an input event to set a variable.

We had a case on discord where we wanted to make a "missed approach light" that lights up when you press "go around" button, and stays on until you climb to your autopilot preselected altitude (the level off after the missed approach). And it should then stay off when you fly a new approach, unless you press the "go around" button again.

This seems like it is not possible right now. 

Button can set the variable to 1, and a led can be lighted by a simple IF statement in the Transform field, comparing current altitude with the altitude preselect.

The LED can be turned off when reaching the level off altitude, but it appears that there is no way to set a simulator/mobiflight  variable without a physical input event (button etc)

**Comment by pizman** [comment]
Hi
I request for this many years ago in the early phase of Mobiflight already.....  But this feature is going lost and forgot within the time.

Maybe we should start another discussion about that, and how we can implement it in a easy and intuitive way.

Just a "improvisional" solution for the moment.

A Change of Data ( Whatever Variable or a Offset/Event currently only happen if a INPUT is done ..... Tech nical by the user while press a Button, turn a encoder or so..... Means the MEGA must detect a physical input ( change of High/Low on a Pin that is defined as a INPUT.

We can do a tricky way now.....
A "Button" is nothing else like a Pin (regulary High) that is wired to GRD.   If it is opulled to GRD this is a Press..... If it lost conecction to GRD that is a release !
A "LED OUTPUT" is otherwise a Pin that is LOW (GRD) if it is controlled "0" by Mobiflight and it is HIGH (5V) if MF tell it to be "1".

So....   Define a "LED Output" on Pin X and a "Button" on Pin Y .....   Wire both Pins together by a Jumper or small Wire.
If the Output Pin is LOW then the imaginary Button is Pressed  if the Output gets High the imaginary Button gets released.
Finally.... Set the "indication" to the Output Pin ( In your case let this Output go OFF (0) in the moment the action should happen)
And set the needed Input to the OnPress of the fictional button on Pin Y.

Result.....   If situation occure the fictional LED on Pin X goes OFF ..... This result in a Change of the fictional Button to GRD and simulate a PRESS Input same way as we would press a Button with our Hand.

Difficult..... But Possible.

**Comment by tigert** [comment]
Pretty insane, but amazing solution at the same time :-)

But I think we need to think of a solution for inputs and outputs that lets us define things like delays and repeat etc, so this migth be part of a bigger branstorming.

**Comment by DocMoebiuz** [comment]
Implemented by #658
