### ISSUE TITLE
Events update directly from Hubhop

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#483]
**Is your feature request related to a problem? Please describe.**
Currently the way to update events in MF relies on having an update previously published. As Hubhop is a live system with additions and modifications being made continuously, the events.txt published is always lagging. Hubhop has a way to export the list, but it cannot place the files where they belong, like the MF internal update does. 

**Describe the solution you'd like**
Revamp the MF internal events update function so that it pulls the latest state of Hubhop into MF automatically and places the files in their proper folders, without user intervention. 

**Describe alternatives you've considered**
The alternative is somewhat cumbersome of manually exporting the three files from Hubhop and then knowing exactly where to move them to. Not good for regular users. 

**Additional context**
Having this function allows one to fix or create new events by experienced users and then just asking the new user to update his events.txt to use the newly created events. No fuzz, no pain, no long explanations.

**Comment by MobiFlight-Admin** [comment]
This way is fairly easy to achieve because we simply have to point MF to the API that exports the data instead of downloading the events from the current github repository.

Via settings menu we can trigger the update exactly the way we are doing it right now.

The whole process still has flaws when things change. But I guess that is also true for the current more static version. When labels change we definitely have an issue because configs will break.

I believe a fully dynamic system would be best with the way to search for definitions on hubhop, get notifications when events got updated with the option to update your config and with notifications when events are not available anymore.

We introduced a unique ID in HubHop for every config so that it should not happen often that the ID will disappear, but it's a use case to keep in mind.


If you believe that it would be helpful to use hubhop in the meantime to download all updated events on demand like it is possible today then we should discuss with @rofl-er and agree, on MobiFlight side the change is fairly easy.

**Comment by rofl-er** [comment]
I like the idea of introducing a new button to download the latest events from hubhop instead from the MF repository. We still need to make the "offline only" users happy. Providing an "online first" solution would be best with means to fall back offline, meaning a user can search and add directly from hubhop when online and fall back to the events.txt files when offline.

As a quick win, we could simply export the required files from the API instead instead of the repo, right?

**Comment by MobiFlight-Admin** [comment]
i actually planned to use the same download buttons and simply point to the hubhop api instead of the repository.

**Comment by tigert** [comment]
This is now released in the beta, but I get a 404 document not found error when trying to download the events.

**Comment by MobiFlight-Admin** [comment]
i can see that there is an "s" extra - no clue how that made it into the code after testing
