### ISSUE TITLE
Still Microsoft Security Warnings in MF Installer 

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#501]
**Describe the bug**
MF Installer still give a Security Warning when we use it first time on a Computer

**Steps To Reproduce**
1. Download the installer from Homepage
2. Run It !
3. To test once again you must download it for new ( whatever the 100% same file).  If you run the original file a second time the warning is gone ( cause you accept it on first run) .....   So simply run a "new" instance and issue occure again.

**Expected behavior**
Would be cool to avoid this..... Cause for new Users without experience in Computers this warning sound like a critical information that MF is Spyware or Hacking Stuff!

**Actual behavior**
Users get scarred    :-)

**Details**
 - MobiFlight Version: ALL
 
**Additional context**
@kkr0kk  still say..... This is related to Microsoft itself and we would need to buy a verification licence!
May a other advanced GitHub User read this and know a way to solve this for free!
(Open Source Freeware is not be able to pay 800$ per Year for this !)
![Issue1](https://user-images.githubusercontent.com/26087116/134676263-f0fbe958-78be-4de9-b027-c4a2b7274d93.PNG)
![issue2](https://user-images.githubusercontent.com/26087116/134676274-a373a13c-d37f-47d9-916c-a183624a8c26.PNG)

**Comment by kkr0kk** [comment]
for my knowledge, toi avoid this we need to sign the APP with an EV certificate, is expensive, and you need legal compagny to get one.

**Comment by kkr0kk** [comment]
I have submit installer to microsoft to up reputation, but i'm not sure the next one will be OK.
And users need to get updates to not have warnings (so maybe some weeks).

mobiflight-installer.exeSubmission ID: e6d8d227-dd30-436a-8fab-6de55c120154Status: CompletedSubmitted by: krok_mor@hotmail.comSubmitted: Sep 23, 2021 18:59:21User Opinion: Incorrect detectionAnalyst comments:

The warning you experienced indicates that the application had not established reputation with the Microsoft Defender SmartScreen Application Reputation feature at that time. We can confirm mobiflight-installer.exe, (SHA256 - cf6e19ce42b45312da77e0cc6035270e820a2115b905cf4fc165c7b23d7bc043) has since established reputation and attempting to download or run the application should no longer show any warnings.

Please note, however, that the submitted files are not signed using a valid digital certificate. Unsigned files will have to establish reputation each time a new version is released.

Application Reputation warnings are meant to indicate when applications do not have known positive reputation. This doesn’t mean that the application is malicious, only that it is “unknown.” Users can still proceed to download and run the application. If establishing reputation immediately is critical, you may want to consider investing in an EV Authenticode certificate. A valid EV Authenticode certificate can immediately establish reputation with SmartScreen reputation services even if no prior reputation exists. In order to be considered a valid EV certificate, the certificate must be issued by a Certificate Authority that is authorized by the Microsoft Trusted Root Certificate Program and recognized as an Extended Validation issuer.

Thank you for contacting Microsoft.


Click here for more information

**Comment by MobiFlight-Admin** [comment]
@kkr0kk - Thank you. Since the installer doesn't update too often I think we give this approach a try. Maybe in the near future there will be a viable way for open source projects to get this kind of certificates for less money.
