### ISSUE TITLE
New input configs aren't recognized until after stopping and running again

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#533]
**Describe the bug**

When a new input is added to a config it won't get recognized until you stop and run the config again

**Steps To Reproduce**
1. Load a config and run it
2. Add a new input config for an axis
3. Try using the axis

Result: "No config found for AnalogInput"
Expected result: It works

If you hit the stop button in the ribbon then the run button again the axis will be recognized and work.

**Comment by MobiFlight-Admin** [comment]
I looked it up and the reason is, that I am keeping a cache for all buttons of the assigned input actions to be faster on the lookup when an event fires. this means that if i hit a button, and I have never seen the button before, I go through all input actions and I check for assignments. I keep a Hash Map with the button ID as key and next time you press the button I will find it faster.

if you have hit a button during run this will create a cache entry with the current assignment snapshot (even if there are none, then it will be empty). Assigning an additional function then requires to stop/start MF so that the cache gets cleared.

We could get rid of the caching entirely... not sure though how the performance will be.

**Comment by neilenns** [comment]
@MobiFlight-Admin Possible fix could just be to clear the cache whenever a new output/input config is added?

**Comment by MobiFlight-Admin** [comment]
@neilenns - can you confirm that it is working on your end too?

**Comment by neilenns** [comment]
@MobiFlight-Admin I don't have an easy way right now, everything on my system is in disarray at the moment!
