### ISSUE TITLE
MF opens dialog warning some boards have old firmware when auto upload is not enabled

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#535]
**Describe the bug**
When opening MF, stops startup with warning that some boards have old firmware even when the auto upload firmware option is not enabled in MF modules window.

**Steps To Reproduce**
1. Start MFConnector (with boards intentionally with older firmware and auto upload firmware disabled)

**Expected behavior**
Startup of MF proceeds without stopping because the autoupload option is disabled (i.e. user has chosen not to update firmware automatically).

**Actual behavior**
The startup of MF is stopped with the dialog box warning that there are boards with old firmware.  User has to press Cancel in order for startup to proceed (wasted time and annoyance).

**Details**
 - MobiFlight Version: 9.0.0.7
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
Default is for auto upload to be enabled, so user willingly has chosen not to update the firmware.  Also, the user is reminded of old firmware in the MF modules window with a yellow badge over the boards with outdated firmware.

**Comment by MobiFlight-Admin** [comment]
I am not sure if i would like to remove this. It is annoying. But I want it to be annoying, because I want everyone to keep their stuff updated.

**Comment by MobiFlight-Admin** [comment]
I think it should not popup if you have autorun enabled. The same is applicable for other dialogs, like orphaned modules, or joysticks.

**Comment by MobiFlight-Admin** [comment]
Hi @JaimeLeon2 - I had to learn that the label of the checkbox was misleading. What it does is enabling whether MobiFlight tries to find Arduinos that have not yet installed the MobiFlight firmware and shows the dialog in case it finds some.

This is not related to the auto-update of the firmware of MobiFlight Boards. That's why the message still shows. I won't plan to provide an option for that but I changed the dialog so that it will auto-close after 5 seconds.
