### ISSUE TITLE
Provide EEPROM restore function in Mobiflight

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#566]
**Is your feature request related to a problem? Please describe.**
Sometimes a Mobiflight module may get a corrupted EEPROM.  Currently there is no way to fix this issue from inside Mobiflight.  The user has to install the Arduino IDE and load the eeprom_clear sketch, to then have to reload the firmware as a brand new board and then finally reload the board configuration.

**Describe the solution you'd like**
I propose that a new button should be added in the Mobilfight modules window to restore the EEPROM of the currently selected module.  This should be easy to implement, as the firmware already includes the EEPROM read and write functions.  The function should first, clear EEPROM before restoring the board SN, Name and firmware version.  The current board configuration should also be restored (maybe as an option?).  All of this information is already contained in the mfmc file.  The board firmware does not require reloading and the board configuration is restored in working order without the known hassles of clearing the EEPROM.

**Describe alternatives you've considered**
Arduino IDE is the alternative, but is a long process and the user has to reload the firmware and the board configuration again.  Not really a good option for regular MF users.

**Additional context**
None

**Comment by pizman** [comment]
Hi....
If i remember right Seb and me talk about that 1-2 Years ago..... may also you was involved....
There was a logical problem that time we not have a good idea to manage....

After the EEPROM Clear ( sketch is set to the board) there must be done a Restart of the Mega ( As i know done in the IDE by using the UPLOAD System itself.

So how should we make this with MF ? .... Pretty sure we could use our system ( same way as we update firmware) to send the EEPROM Clear Sketch....  And we could also trigger the restart same way.
BUT. .... Then the Board is "new"  And it is technical no longer shown in MF.   

In the past we thought it will be possible if the user THEN Restart MF by hand.....  But Seb wants a fully automatic process.
So....  Should MF in the fututre make the initialize process a second time to detect the "now new" Mega again ?

Also about the Automatic Device Restore..... I think a wonderfull idea..... But how should MF "know" the stored data ?
We can not read them from the board in case the Board is still corrupted in the moment we use that tool.
Otherwise MF can not know what MFMC File stored the needed data for taht board !

*****
So nice idea..... I fully agree and looking forward to it.   But i see some problems in the posibility..... right ?

**Comment by JaimeLeon2** [comment]
What I had in mind is using the MF firmware eeprom read and write functions to first read the entire eeprom region and wherever location the read byte is not 255, write back 255. This is what the eeprom clear sketch does. Then write the eeprom "header" that contains the name, SN and version. This function already exists and is used on new boards, except in this case the info will come from the mfmc file. Lastly restore the device configs which is also an existing function.
All done within mobiflight. No sketch to load and no reset needed. The only missing piece is the eeprom clear which IMO is very easy.

**Comment by elral** [comment]
It is only required to write a 0x00 to the first loacation of the config in the EEPROM. An following config read gets this NULL as first byte and the config is interpeted as empty.
The best way to do this would be a new function in the FW (new command) which will be activated by the connector.

Remark:
In the actual FW after uploading the FW on a new board the first read of the config results in transferring of MEMLEN_CONFIG (256 for promicro) times 0xFF as the EEPROM is also cleared (0xFF). This is not recognized by the user as the connector interprets this as empty config.
With the new (for now) beta FW this has changed. After first upload of a new FW and the EEPROM contains NO serial number, a serial number is created (like always) and the first byte of the config in the EEPROM is set to 0x00 to avoid transfering a config with only 0xFF.
Furthermore I have the hope that with the other changes a corrupted EEPROM will not happen anymore (but we will see).

**Comment by DocMoebiuz** [comment]
I will close this, FW is now way more stable with all the improvements and https://github.com/MobiFlight/MobiFlight-Connector/issues/177 would be still a way for the user to start over from scratch.
