### ISSUE TITLE
Remove Serial Number from Drop Down Labels for MobiFlight Modules and Joysticks

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#585]
**Is your feature request related to a problem? Please describe.**
Remove Serial Number from Drop Down Labels for MobiFlight Modules and Joysticks

**Describe the solution you'd like**
The labels should simply show the name, because it doesn't help much anyways to show the cryptic serial to the user.

**Describe alternatives you've considered**
Still show it. 
Show the COM Port for default Names, so that MobiFlight Boards can be told apart from each other.

- [x] Config Wizard Dialog - Display Modules
- [x] InputConfig Wizard Dialog -  Modules
- [x] -Orphaned Serials Dialog- Serial number will still be displayed because it is important for correct mapping

**Comment by neilenns** [comment]
I can knock this one out

**Comment by neilenns** [comment]
Uuuuugh. This is not a straightforward thing @MobiFlight-Admin. Just removing the text from the dropdown label causes all sorts of problems:

1. Saved config files no longer properly populate the dialogs when you open them, since the identifier in the .mcc file is the name + serial number.
2. After selecting one of the entries in the device dropdown the modules dropdown doesn't populate.

Turns out there's quite a bit of logic that depends on the serial number being present in that dropdown label :(

Unassigning and kicking this back into the pool for people to consider. Not sure it's worth the effort to change anymore.

**Comment by DocMoebiuz** [comment]
Haha, ok - there is a difference between value and label... if we use proper ListItems it should be doable pretty easily. but it is quire repetitive
