### ISSUE TITLE
Adding devices under circumstances causes an exception

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-Connector#625]
**Describe the bug**
Adding devices to a module sometime causes an exception depending on which UI items happen to be selected.

**Steps To Reproduce**

***Scenario 1 (OK):***
- Open `(Settings/)Mobiflight` module dialog.
- DO NOT expand the device tree on a module, or alternatively: EXPAND the tree and SELECT a child (device) entry
- Right click on the `Modules` entry and add a device

Result:
- everything works as expected 

***Scenario 2 (BUG):***
- Open `(Settings/)Mobiflight` module dialog.
- expand module tree; DO NOT select a child entry
- Right click on the `Modules` entry and add a device

Result:
- `System.NullReferenceException` in `MobiFlightPanel.cs`, line 366 (`getVirtualModuleFromTree()` returns null)

See submitted PR #626 for fix.

**Details**
 - MobiFlight Version: 9.2

**Comment by pizman** [comment]
Nice i found this Issue Report.
Still make a Screenshot some Mins ago and would like to Report the same bahavour.

Do you guys still find a way to reproduce ?  Or better do you know WHEN the Bug is happen 100%

Yesterday i got it by testing ~~  4 of 10 Trys....  But i not know what have changed in the trys ?
If it work, then it work all time.... Only a Restart ( Reconnect of Mega) could happen it again.
BUT
Today....  50 Trys.... No Bug !

**Comment by GioCC** [comment]
Unfortunately I discovered a further bug in this fix - will post issue and fix shortly.
