### ISSUE TITLE
Allow to trigger Input Action on SimVariable or MobiFlight Variable Change

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#658]
**Is your feature request related to a problem? Please describe.**
Currently we can only read variables from the Sim or MF Variables and then use them for Output Devices. There are use cases, where we would like to trigger an action in the Sim, something that could be done by an input action.

**Describe the solution you'd like**
Currently we have Button, Encoder and AnalogInput as devices that can be assigned with an Input Action.
If we add another type, e.g. called "Config Reference" then we could treat it similar to a AnalogInput device. The only thing that we have to do is to make sure the correct OnChange event gets triggered.

**Describe alternatives you've considered**
Where we today select an output device, we would just have to be able to select an Input action. And then we treat the variable change like an onChange from a potentiometer. This will allow for most flexibility.

**Additional context**

**Comment by DocMoebiuz** [comment]
implements #456

**Comment by neilenns** [comment]
There are a couple of issues I noticed with this change:

1. If you're doing a 7-segment LED display the settings you configure aren't applied when you re-open the dialog to make changes in the future.
2. There's text clipping on the "Use left padding" label

**Comment by DocMoebiuz** [comment]
@neilenns I can't reproduce the 7 segment config problem. For me it is saving perfectly fine. Is there anything else to do specifically to trigger the behavior? Can you give step by step instructions please.

**Comment by DocMoebiuz** [comment]
@neilenns I swear i cannot reproduce it following exactly your steps or doing anything else.

**Comment by neilenns** [comment]
I'll debug it a bit later today and figure out what is going on

**Comment by neilenns** [comment]
Ok this happens when you have a stepper configured on the board. If there's no stepper configured it's fine.

1. Configure an Arduino with both a stepper module and a 7-segment display
2. Create a new output config
3. Set the simconnect var to custom code (A:PLANE ALTITUDE, feet)
4. On the display tab select a display module with the following options: Number of digits 5, Use left padding on and set to space, use display all five digits, and reverse digits
5. Hit Ok
6. Open the dialog again

Result: None of your configuration for the 7 segment display shows.

When this line of code runs:

https://github.com/MobiFlight/MobiFlight-Connector/blob/2ad26e8142a3d7cd138c97fcdff0af2985462b75/UI/Panels/OutputWizard/DisplayPanel.cs#L151

and the board is configured with a stepper it causes the `StepperPanel_OnStepperSelected()` method to run. That method calls `syncToConfig()` which throws an exception here:

https://github.com/MobiFlight/MobiFlight-Connector/blob/454edbe28ce6efc830f8256ff3548e7d412599d7/UI/Panels/Output/DisplayLedDisplayPanel.cs#L162
