### ISSUE TITLE
Set filters only after pressing OK in Output config

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#744]
**Is your feature request related to a problem? Please describe.**
In output config, selecting an event immediately sets the filters for that particular event, losing all search results that had been presented with the original search criteria. If the user selected the wrong event, he now has to reset and again make a new search. 

**Describe the solution you'd like**
Allow selecting the event from the drop down of search results as currently done, but delay setting the filters, keeping the search results, until the user clicks on OK. This way, if the user did not select the correct event, he can reopen the drop down with the search results and pick another event or maybe refine the search criteria. 

**Describe alternatives you've considered**
Alternative is to reset the filters and begin a new search with the same criteria as before. 

**Additional context**
None

**Comment by JaimeLeon2** [comment]
***An additional request related to this issue.
It appears that when the config has an already selected event and the user inputs custom code, the filters and selected event are retained.  The customized code flag is not activated.  The only way I have found to activate the customized code flag is by resetting the filters, deselecting the event and reentering the custom code.  From the UI, you cannot tell that you actually have custom code in the code box.

Customized code flag should be activated whenever custom code is detected, and if the filters are set, they should be reset and the currently selected event should be deselected and blanked out.

**Comment by DocMoebiuz** [comment]
I will address the first issue.

I won't address the second issue. I don't think it helps enough. If you choose a preset and then you decide to change it, so that it works, there is no real need to now flag it as a custom preset imho. I am also not sure how I determine whether it is a customized preset or not. Maybe you customize it and it turns out that the preset exists?

So once you close the dialog and when you load it next time, it will either show as custom preset or it will find a preset that has the same code.

I will better fix the load by code routine instead.
