### ISSUE TITLE
Release notes is hard to find

### ISSUE THREAD

**Issue by storeilly** [MobiFlight/MobiFlight-Connector#911]
**Is your feature request related to a problem? Please describe.**
After automatic update the release notes gets clicked away or doesn't appear I don't remember, but I went searching in the files of the installation but could not find them.

**Describe the solution you'd like**
I'd like a link to the release notes page [(https://www.mobiflight.com/en/download.html)] included on the about page please. OR possibly a text file within the install folder that can be found or even opened from the GUI.

**Describe alternatives you've considered**
I searched the files installed and could not find anything, I also searched the github issues. I eventually found a link to the download mentioned in a post on the forum referencing the release notes.

**Additional context**

**Comment by DocMoebiuz** [comment]
Hi! The release notes are typically in two places:

* the Mobiflight website: https://mobiflight.com/download.html

* on github under releases: https://github.com/MobiFlight/MobiFlight-Connector/releases


I think it's a great idea to add the link to one of them (probably github) in the menu because the release notes are only displayed on first start after the update
