### ISSUE TITLE
Changing the name of the MF installer disrupts the installation process

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-Connector#912]
The MF install executable has to be called exactly `MobiFlight-Installer.exe`; renaming it prevents the installation process to complete correctly.
There should be no reason to rename the installation file, however it might happen that the user wants to add a download date/version number (even if pointless) or has e.g. a "(1)" suffix appended from multiple downloads. 
Seeing the installation fail is then unlikely connected to the fact that the name has been changed.

1. Download the installer from the official website
2. Rename it and copy it to any convenient work directory
3. Launch the installer
4. After extracting a few files, the installer will issue an "unhandled exception" error (Can't find the specified file); if the error is ignored, the process gets stuck.
6. On a second attempt, deleting all files except the installer and the auto-downloaded .zip file, relaunch the installer; this time it remains stuck with no error message.

Intended behaviour:
Perform the install process normally even if the original file is renamed, or otherwise check the executable name and gracefully warn the user to restore the correct original name prior to launch.

 - MobiFlight Version: 9.5.0

**Comment by DocMoebiuz** [comment]
mobiflight-installer is also used for the update which might be the case that it wont work.
this is in deed inconvenient. but even if we change it so that it uses it's own process name, the auto-update will also break.

I think this will be fixed if we have an actual setup process that installs the installer and then starts it.

I am assuming that not too many users have this issue, so I will close this one in favor of #953
